# Development Compose File, could be used as a guideline to deploy DockerRight
services:
  prod:
    container_name: dockerright
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    # image: ghcr.io/bata94/dockerright:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup:/opt/DockerRight/backup
      - ./config:/opt/DockerRight/config
    environment:
      TZ: Europe/Berlin

  dev:
    container_name: dockerright
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup:/opt/DockerRight/backup
      - ./config:/opt/DockerRight/config
      - ./:/opt/DockerRight
    environment:
      TZ: Europe/Berlin
      LOG_LEVEL: "info"
      ENABLE_BACKUP: false
      ENABLE_MONITOR: false
      BACKUP_ON_STARTUP: false
      CREATE_TEST_CONTAINER_ON_STARTUP: false
      BEFORE_BACKUP_CMD: "uname -a"
      AFTER_BACKUP_CMD: "ls -al /opt/DockerRight/backup"
      BACKUP_PATH: "/opt/DockerRight/backup"
      BACKUP_HOURS: "[2,4,6,8,10]"
      MONITOR_INTERVAL_SECONDS: 10
      MONITOR_RETIES: 3
      RETENTION_HOURS: 24
      CONCURRENT_BACKUP_CONTAINERS: 1
