services:
  prod:
    container_name: dockerright
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup:/opt/DockerRight/backup
      - ./config:/opt/DockerRight/config
    environment:
      TZ: Europe/Berlin

  dev:
    container_name: dockerright
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup:/opt/DockerRight/backup
      - ./config:/opt/DockerRight/config
      - ./:/opt/DockerRight
    environment:
      TZ: Europe/Berlin

