# Development Compose File, could be used as a guideline to deploy DockerRight
services:
  prod:
    container_name: dockerright
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   target: prod
    # image: ghcr.io/bata94/dockerright:latest
    image: dr_test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup:/opt/DockerRight/backup
      - ./config:/opt/DockerRight/config
    environment:
      TZ: Europe/Berlin

  dev:
    container_name: dockerright
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup:/opt/DockerRight/backup
      - ./config:/opt/DockerRight/config
      - ./:/opt/DockerRight
    environment:
      TZ: Europe/Berlin
      LOG_LEVEL: "info"
      ENABLE_BACKUP: true
      ENABLE_MONITOR: false
      BACKUP_ON_STARTUP: true
      CREATE_TEST_CONTAINER_ON_STARTUP: true
      BEFORE_BACKUP_CMD: "uname -a"
      AFTER_BACKUP_CMD: "ls -al /opt/DockerRight/backup"
      BACKUP_PATH: "/opt/DockerRight/backup"
      BACKUP_HOURS: "[0,2,4,6,8,10,12,14,16,18,20,22]"
      MONITOR_INTERVAL_SECONDS: 60
      MONITOR_RETIES: 5
      RETENTION_HOURS: 24
      CONCURRENT_BACKUP_CONTAINERS: 8
